module.exports = Object.freeze({
    PROJECT_ID: 'chatbot-235714',
    SESSION_ID: '123456',
    LANGUAGE_CODE: 'en-US',
    WELCOME_ACTION: 'input.welcome',
    SET_REMINDER_ACTION: 'setReminder',
    GET_REMINDERS: 'getReminders',
    GREETING_PAYLOAD: 'Greeting',
    CREATE_REMINDER: 'Set a reminder',
    SHOW_ALL_REMINDERS: 'Show all reminders',
    PROCESS_HOOK_ERROR: 'Process hook error. Details: ',
    POSTBACK_BUTTON_TYPE: 'postback',
    RESPONSE_MESSAGE_TYPE: 'RESPONSE',
    BUTTON_TEMPLATE_TYPE: 'button',
    VERIFY_TOKEN: 'marker',
    HUB_MODE: 'hub.mode',
    HUB_TOKEN: 'hub.verify_token',
    HUB_CHALLENGE: 'hub.challenge',
    CONTENT_TYPE : {
    	JSON: 'application/json'
    },
    ACCEPT_REMINDER: 'Accept',
    ACCEPT_ACTION: 'accept',
    SNOOZE_REMINDER: 'Snooze',
    SNOOZE_ACTION: 'snooze',
    SNOOZE_CONTEXT: 'snooze',
    DEFAULT_TIMEZONE: 'Europe/Warsaw',
    ALARM_IMG_LINK: 'https://lh3.googleusercontent.com/uD65OOIxM1-khzDI5OowwdzjD9j8CgelcH9mBGAZWIAsAyoTtEE7smUH9GAf3mCg8AA=s180-rw',
    EMPTY_LIST: 'The reminder list is empty'
});
